DELETE FROM FILM_LIKES;
DELETE FROM FILMS_GENRE;
DELETE FROM MODEL_FILM;
DELETE FROM MODEL_USER;
DELETE FROM USERS_FRIENDS;
ALTER TABLE MODEL_FILM ALTER COLUMN FILM_ID RESTART WITH 1;
ALTER TABLE MODEL_USER ALTER COLUMN USER_ID RESTART WITH 1;


